// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadNetmon returns the embedded CollectionSpec for netmon.
func loadNetmon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetmonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load netmon: %w", err)
	}

	return spec, err
}

// loadNetmonObjects loads netmon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netmonObjects
//	*netmonPrograms
//	*netmonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetmonObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetmon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netmonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonSpecs struct {
	netmonProgramSpecs
	netmonMapSpecs
	netmonVariableSpecs
}

// netmonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonProgramSpecs struct {
	CountPackets  *ebpf.ProgramSpec `ebpf:"count_packets"`
	MonitorEgress *ebpf.ProgramSpec `ebpf:"monitor_egress"`
}

// netmonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonMapSpecs struct {
	OutgoingAddr *ebpf.MapSpec `ebpf:"outgoing_addr"`
	PktCount     *ebpf.MapSpec `ebpf:"pkt_count"`
}

// netmonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonVariableSpecs struct {
}

// netmonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonObjects struct {
	netmonPrograms
	netmonMaps
	netmonVariables
}

func (o *netmonObjects) Close() error {
	return _NetmonClose(
		&o.netmonPrograms,
		&o.netmonMaps,
	)
}

// netmonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonMaps struct {
	OutgoingAddr *ebpf.Map `ebpf:"outgoing_addr"`
	PktCount     *ebpf.Map `ebpf:"pkt_count"`
}

func (m *netmonMaps) Close() error {
	return _NetmonClose(
		m.OutgoingAddr,
		m.PktCount,
	)
}

// netmonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonVariables struct {
}

// netmonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonPrograms struct {
	CountPackets  *ebpf.Program `ebpf:"count_packets"`
	MonitorEgress *ebpf.Program `ebpf:"monitor_egress"`
}

func (p *netmonPrograms) Close() error {
	return _NetmonClose(
		p.CountPackets,
		p.MonitorEgress,
	)
}

func _NetmonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netmon_bpfeb.o
var _NetmonBytes []byte
